In [1]:
#initialize

import pandas as pd
thisyear = '2022'
#mortfile2018 = 'Resources/Mort2018US.PubUse.txt'
#mortfile2018parquet = mortfile2018.replace('.txt','.parquet')
#mortfile2018csv = mortfile2018.replace('.txt','.csv')
#mortfile2022 = 'Resources/Mort2019US.PubUse.txt'
#mortfile2019parquet = mortfile2019.replace('.txt','.parquet')
#mortfile2019csv = mortfile2019.replace('.txt','.csv')
#mortfile2020 = 'Resources/Mort2020US.PubUse.txt'
#mortfile2020parquet = mortfile2020.replace('.txt','.parquet')
#mortfile2020csv = mortfile2020.replace('.txt','.csv')
#mortfile2022 = 'Resources/Mort2022US.PubUse.txt'
#mortfile2022parquet = mortfile2022.replace('.txt','.parquet')
#mortfile2022csv = mortfile2022.replace('.txt','.csv')
mortfile2022 = 'Resources/Mort2022US.PubUse.txt'
mortfile2022parquet = mortfile2022.replace('.txt','.parquet')
mortfile2022csv = mortfile2022.replace('.txt','.csv')

In [2]:
# define dataset.  this is a fixed width text file

fieldwidths = [
(0,19),
(19,20),
(20,60),
(60,62),
(62,63),
(63,64),
(64,66),
(66,68),
(68,69),
(69,70),
(70,71),
(71,72),
(72,73),
(73,74),
(74,76),
(76,78),
(78,80),
(80,82),
(82,83),
(83,84),
(84,85),
(85,101),
(101,105),
(105,106),
(106,107),
(107,108),
(108,109),
(109,143),
(143,144),
(144,145),
(145,149),
(149,152),
(152,153),
(153,156),
(156,159),
(159,161),
(161,162),
(162,164),
(164,171),
(171,178),
(178,185),
(185,192),
(192,199),
(199,206),
(206,213),
(213,220),
(220,227),
(227,234),
(234,241),
(241,248),
(248,255),
(255,262),
(262,269),
(269,276),
(276,283),
(283,290),
(290,297),
(297,304),
(304,340),
(340,342),
(342,343),
(343,348),
(348,353),
(353,358),
(358,363),
(363,368),
(368,373),
(373,378),
(378,383),
(383,388),
(388,393),
(393,398),
(398,403),
(403,408),
(408,413),
(413,418),
(418,423),
(423,428),
(428,433),
(433,438),
(438,443),
(443,444),
(444,446),
(446,447),
(447,448),
(448,449),
(449,450),
(450,483),
(483,486),
(486,487),
(487,488)
]

fieldnames = [
'blank',
'res_status',
'blank2',
'ed_v89',
'ed_v03',
'ed_flag',
'death_month',
'blank3',
'sex',
'age_years',
'age_months',
'age_3',
'age_4',
'age_sub_flag',
'age_recode_52',
'age_recode_27',
'age_recode_12',
'infant_age_recode_22',
'place_of_death',
'marital_status',
'death_day',
'blank4',
'current_year',
'work_injury',
'death_manner',
'disposition',
'autopsy',
'blank5',
'activity_code',
'place_injured',
'icd_cause_of_death',
'cause_recode358',
'blank6',
'cause_recode113',
'infant_cause_recode130',
'cause_recode39',
'blank7a',
'num_entity_axis',
'cond1',
'cond2',
'cond3',
'cond4',
'cond5',
'cond6',
'cond7',
'cond8',
'cond9',
'cond10',
'cond11',
'cond12',
'cond13',
'cond14',
'cond15',
'cond16',
'cond17',
'cond18',
'cond19',
'cond20',
'blank7',
'num_rec_axis_cond',
'blank8',
'acond1',
'acond2',
'acond3',
'acond4',
'acond5',
'acond6',
'acond7',
'acond8',
'acond9',
'acond10',
'acond11',
'acond12',
'acond13',
'acond14',
'acond15',
'acond16',
'acond17',
'acond18',
'acond19',
'acond20',
'blank9',
'race',
'bridged_race_flag',
'race_imp_flag',
'race_recode3',
'race_recode5',
'blank10',
'hisp',
'blank11',
'hisp_recode'
]

fieldtypes= {
#'blank':str,
'res_status':str,
#'blank2':str,
'ed_v89':str,
'ed_v03':str,
'ed_flag':str,
'death_month': int,
#'blank3':str,
'sex':str,
'age_years':int,
'age_months':int,
'age_3':str,
'age_4':str,
'age_sub_flag':str,
'age_recode_52':str,
'age_recode_27':str,
'age_recode_12':str,
'infant_age_recode_22':str,
'place_of_death':str,
'marital_status':str,
'death_day':str,
#'blank4':str,
'current_year':str,
'work_injury':str,
'death_manner':str,
'disposition':str,
'autopsy':str,
#'blank5':str,
'activity_code':str,
'place_injured':str,
'icd_cause_of_death':str,
'cause_recode358':str,
#'blank6':str,
'cause_recode113':str,
'infant_cause_recode130':str,
'cause_recode39':str,
#'blank7a':str,
'num_entity_axis':str,
'cond1':str,
'cond2':str,
'cond3':str,
'cond4':str,
'cond5':str,
'cond6':str,
'cond7':str,
'cond8':str,
'cond9':str,
'cond10':str,
'cond11':str,
'cond12':str,
'cond13':str,
'cond14':str,
'cond15':str,
'cond16':str,
'cond17':str,
'cond18':str,
'cond19':str,
'cond20':str,
#'blank7':str,
'num_rec_axis_cond':str,
#'blank8':str,
'acond1':str,
'acond2':str,
'acond3':str,
'acond4':str,
'acond5':str,
'acond6':str,
'acond7':str,
'acond8':str,
'acond9':str,
'acond10':str,
'acond11':str,
'acond12':str,
'acond13':str,
'acond14':str,
'acond15':str,
'acond16':str,
'acond17':str,
'acond18':str,
'acond19':str,
'acond20':str,
#'blank9':str,
'race':str,
'bridged_race_flag':str,
'race_imp_flag':str,
'race_recode3':str,
'race_recode5':str,
#'blank10':str,
'hisp':str,
'blank11':str,
'hisp_recode':str
}

In [3]:
# Now read in the data

# read the csv file ONLY ONCE, the first time.  after it is saved in parquet format, load it from the parquet file!
mort2022_df = pd.read_fwf(mortfile2022, colspecs=fieldwidths, dtype=fieldtypes, names=fieldnames, encoding='latin-1')
#mort2022_df = pd.read_parquet(mortfile2022parquet)

print(f'Read in file {mortfile2022}, collected {len(mort2022_df)} rows.')

Read in file Resources/Mort2022US.PubUse.txt, collected 3289569 rows.

In [4]:
# write the dataframe to a parquet file, for much faster loading next time.  Do this only the very first time retrieving data
mort2022_df.to_parquet(mortfile2022parquet, engine='pyarrow')

In [5]:
# clean up the data by removing blanks etc
columns_to_drop = ['blank','blank2','blank3','blank4','blank5','blank6','blank7a','blank7','blank8','blank9','blank10','blank11']
mort2022_df = mort2022_df.drop(columns_to_drop, axis=1)
mort2022_df.columns

Index(['res_status', 'ed_v89', 'ed_v03', 'ed_flag', 'death_month', 'sex',
       'age_years', 'age_months', 'age_3', 'age_4', 'age_sub_flag',
       'age_recode_52', 'age_recode_27', 'age_recode_12',
       'infant_age_recode_22', 'place_of_death', 'marital_status', 'death_day',
       'current_year', 'work_injury', 'death_manner', 'disposition', 'autopsy',
       'activity_code', 'place_injured', 'icd_cause_of_death',
       'cause_recode358', 'cause_recode113', 'infant_cause_recode130',
       'cause_recode39', 'num_entity_axis', 'cond1', 'cond2', 'cond3', 'cond4',
       'cond5', 'cond6', 'cond7', 'cond8', 'cond9', 'cond10', 'cond11',
       'cond12', 'cond13', 'cond14', 'cond15', 'cond16', 'cond17', 'cond18',
       'cond19', 'cond20', 'num_rec_axis_cond', 'acond1', 'acond2', 'acond3',
       'acond4', 'acond5', 'acond6', 'acond7', 'acond8', 'acond9', 'acond10',
       'acond11', 'acond12', 'acond13', 'acond14', 'acond15', 'acond16',
       'acond17', 'acond18', 'acond19', 'acond20', 'race', 'bridged_race_flag',
       'race_imp_flag', 'race_recode3', 'race_recode5', 'hisp', 'hisp_recode'],
      dtype='object')

In [6]:
#mort2018_df = mort2018_df.drop('blank11',axis=1)
print('shape before',mort2022_df.shape)
mort2022_df.dropna(axis=1, how='all')
print('shape after',mort2022_df.shape)

shape before (3289569, 79)
shape after (3289569, 79)

In [7]:
#create summary df, by month, contains counts of deaths, count of cataclysmic storm deaths, stroke, heart attack, exposure

deathcounts = [0,0,0,0,0,0,0,0,0,0,0,0]
avg_age = [0,0,0,0,0,0,0,0,0,0,0,0]
cause_cataclysmic = [0,0,0,0,0,0,0,0,0,0,0,0] 
cause_heart = [0,0,0,0,0,0,0,0,0,0,0,0] 
cause_stroke = [0,0,0,0,0,0,0,0,0,0,0,0]  

i = 0

for index, row in mort2022_df.iterrows():
    thismonth = int(row['death_month'])-1
    deathcounts[thismonth] += 1
    if row['cause_recode358'] == '418':
        cause_cataclysmic[thismonth] += 1
    if row['cause_recode39'] == '018' or row['cause_recode39'] == '019' or row['cause_recode113'] == '054' or row['cause_recode113'] == '053' \
        or row['cause_recode358'] == '210' or row['cause_recode358'] == '229' or row['infant_cause_recode130'] == '046' \
        or row['infant_cause_recode130'] == '050':
        cause_heart[thismonth] += 1
    if row['cause_recode39'] == '024' or row['infant_cause_recode130'] == '031' or row['cause_recode358'] == '234':
        cause_stroke[thismonth] += 1
    i += 1
    #if i>10000: break

print('finished loop')
print(deathcounts)
print('cataclysm',cause_cataclysmic)
print('heart',cause_heart)
print('stroke',cause_stroke)

finished loop
[370382, 291050, 268937, 246767, 255125, 249011, 261015, 259791, 251649, 265718, 268826, 301298]
cataclysm [5, 4, 12, 6, 8, 2, 39, 8, 45, 37, 7, 40]
heart [0, 0, 1, 0, 3, 1, 1, 0, 1, 1, 0, 3]
stroke [5, 5, 11, 1, 8, 8, 5, 7, 7, 3, 6, 3]

In [8]:
months = [1,2,3,4,5,6,7,8,9,10,11,12]
years = [2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022,2022]
summary2022_df = pd.DataFrame({'year':years,'month':months,'deaths':deathcounts, 'cause_cataclysm':cause_cataclysmic, \
                               'cause_heart':cause_heart, 'cause_stroke':cause_stroke})
summary2022_df

    year  month  deaths  cause_cataclysm  cause_heart  cause_stroke
0   2022      1  370382                5            0             5
1   2022      2  291050                4            0             5
2   2022      3  268937               12            1            11
3   2022      4  246767                6            0             1
4   2022      5  255125                8            3             8
5   2022      6  249011                2            1             8
6   2022      7  261015               39            1             5
7   2022      8  259791                8            0             7
8   2022      9  251649               45            1             7
9   2022     10  265718               37            1             3
10  2022     11  268826                7            0             6
11  2022     12  301298               40            3             3

In [9]:
summary2022_df.to_csv(mortfile2022csv)